name: Upload Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Create .env file
        run: |
          echo "VITE_GAMES_API=${{ secrets.VITE_GAMES_API }}" >> .env
          echo "VITE_USER_API=${{ secrets.VITE_USER_API }}" >> .env
          echo "VITE_MARKETPLACE_API=${{ secrets.VITE_MARKETPLACE_API }}" >> .env

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: List files
        run: ls -R

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          SOURCE_DIR: dist/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}